apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgCL0M+ro6Ed7ZUDqHUB+aOspYWsHsSqjVEGSP8OLdDUi2XKUT+BbIx/ycwyff9P4DUO+ZSKTuDBK/LG06X9Ti1ANcQB4oNcpopOf/zt8SHtAgnXByEeMN5UGGDz1CMDvU01QZ/RWPDWMMet3KFXKgWvtNkakDMLyfwNaPWJc63JNsi2U+YngngPYVbZZywz50wW9Q++bomt7nNcLdaAC4EkXQgBqJ4m3uUVlUS/JHQKDCCQEHGunenNR7UxBArxeO9mlSZUN63KLKvR0VlTTFPpbE7VHIKvkazo/q8tnGoh3ZK0P+82xVwVlJO7smwpGVwb+JNU1wZRtp5xRLU2vNSYI6TvEAzFas15EQytofq587w21BND7nVFq7wu0te1R2Il1h9TSHXkQ1sBAt2mBi0FL/pehUV+CrEbqLU18Tdq1wC8YHPo01iMqYMnxHOfTWu32oSratmOuugGRf8bpkPE18DBLyT6EunI+S+ZpsC3dA6CbmedCTq81FXvKcfTRRXSHnUumUZjBfJEFlpvkquXaJXZ3UZhg8e4rjtfSF5RYykjksN708R6ZTIoUh5T7FxLODzTD//05GKTZYSCkORiA3fhy6q/OkYpDzC4PBiDKmYV1yd5KskO+AuJO+4ViWYSmTkmkXYBUmU5VGpvlHl34zZxZbfkcgrIKwx1emmYwSWUTtdwsx9zJ8Qr60V3UzUZqRytXYEkRZQMW3BoXMTtJRsKtRqvX2Ty6vsY/0fIcPIyrP+UJqBr
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: cloudflare-api-token-secret
      namespace: cert-manager
