apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-tunnel
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ..
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: "git@github.com:TAK848/k8s-home-apps.git"
    path: apps/cloudflared-tunnel/base
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared-tunnel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
