apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homenw
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ..
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: "git@github.com:TAK848/k8s-home-apps.git"
    path: apps/homenw/base
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: homenw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
