apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ..
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: "git@github.com:TAK848/k8s-home-apps.git"
    path: longhorn/overlays/home
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # managedNamespaceMetadata:
    #   labels: # The labels to set on the application namespace
    #     any: label
    #     you: like
    #   annotations: # The annotations to set on the application namespace
    #     the: same
    #     applies: for
    #     annotations: on-the-namespace
