apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared-tunnel
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cloudflared-tunnel-vault-auth
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: k8s-cloudflared-tunnel-path
  kubernetes:
    role: cloudflared-tunnel-role
    serviceAccount: cloudflared-tunnel
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflared-tunnel-static-secret
spec:
  vaultAuthRef: cloudflared-tunnel-vault-auth
  mount: homek8s
  path: cloudflared-tunnel/k8s-home-credentials
  type: kv-v2
  refreshAfter: 60s
  destination:
    create: true
    name: cloudflared-tunnel-secret # secret name
