apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
- namespace.yaml
- ../../../components/minio
- ../../../components/grafana-loki
- ../../../components/grafana-agent
- ../../../components/grafana-agent-operator/resources
- ../../../components/grafana
# - ../../../components/prometheus-stack
- ../../../components/prometheus-stack/resources
- ../../../components/promtail
# - ../../../components/prometheus
# - ../../../components/prometheus-operator
# - ../../../components/alertmanager
# - ../../../components/kube-state-metrics
# - ../../../components/node-exporter
# - ../../../components/velero
# - ../../../components/velero-plugin-for-aws
# - ../../../components/velero-plugin-for-gcp
# - ../../../components/velero-plugin-for-microsoft-azure
# patches:
# - path: common.yaml
replacements:
- path: replace-minio-ns.yaml
# - source:
#     fieldPath: metadata.namespace
#     group: apps
#     kind: StatefulSet
#     name: minio
#     version: v1
#   targets:
#   - fieldPaths:
#     - spec.template.spec.containers.0.command.2
#     options:
#       delimiter: .
#       index: 6
#     select:
#       group: apps
#       kind: StatefulSet
#       name: minio
#       version: v1
