version: '3'

tasks:
  hello:
    cmds:
    - echo 'Hello World from Task!'
    silent: true
  update-metallb:
    cmds:
    - helm template metallb metallb/metallb -f components/metallb/upstream/values.yaml  > components/metallb/upstream/install.yaml
    silent: false
