version: '3'

tasks:
  hello:
    cmds:
    - echo 'Hello World from Task!'
    silent: true
  update-argocd:
    cmds:
    - helm template argocd argo/argo-cd -f components/argocd/upstream/values.yaml > components/argocd/upstream/install.yaml
    silent: false
  update-metallb:
    cmds:
    - helm template metallb metallb/metallb -f components/metallb/upstream/values.yaml  > components/metallb/upstream/install.yaml
    silent: false
  update-logging:
    cmds:
    - helm template loki grafana/loki -n logging -f components/grafana-loki/upstream/values.yaml  > components/grafana-loki/upstream/install.yaml
    - helm template minio minio/minio -n MINIO_NAMESPACE_PLACEHOLDER -f components/minio/upstream/values.yaml  > components/minio/upstream/install.yaml
    - helm template grafana-agent -n logging grafana/grafana-agent -f components/grafana-agent/upstream/values.yaml > components/grafana-agent/upstream/install.yaml
    - helm template grafana grafana/grafana -n logging -f components/grafana/upstream/values.yaml  > components/grafana/upstream/install.yaml
    - helm template prometheus prometheus-community/prometheus -n logging -f components/prometheus/upstream/values.yaml  > components/prometheus/upstream/install.yaml
    - helm template kube-prometheus-stack prometheus-community/kube-prometheus-stack -n logging -f components/prometheus-stack/resources/upstream/values.yaml > components/prometheus-stack/resources/upstream/install.yaml
    - helm show crds prometheus-community/kube-prometheus-stack > components/prometheus-stack/crds/upstream/crds.yaml
    - helm template promtail grafana/promtail -n logging -f components/promtail/upstream/values.yaml  > components/promtail/upstream/install.yaml
    - helm template grafana-agent-operator grafana/grafana-agent-operator -n logging -f components/grafana-agent-operator/resources/upstream/values.yaml > components/grafana-agent-operator/resources/upstream/install.yaml
    - helm show crds grafana/grafana-agent-operator > components/grafana-agent-operator/crds/upstream/crds.yaml
    - yq eval 'select(.metadata.name | test(".*\.coreos\.com$") | not)' components/grafana-agent-operator/crds/upstream/crds.yaml > components/grafana-agent-operator/crds/upstream/filtered-crds.yaml

    silent: false
  update-vault:
    cmds:
    - helm template vault hashicorp/vault -f components/vault/upstream/values.yaml > components/vault/upstream/install.yaml
    - helm template vso hashicorp/vault-secrets-operator -f components/vault-secrets-operator/upstream/values.yaml --include-crds > components/vault-secrets-operator/upstream/install.yaml
    silent: false
  update-mysql-operator:
    cmds:
    - helm template mysql-operator mysql-operator/mysql-operator -n mysql-operator -f components/mysql-operator/upstream/values.yaml --include-crds > components/mysql-operator/upstream/install.yaml
    silent: false
  update-mysql-innodbcluster:
    cmds:
    - helm template mysql-innodbcluster mysql-operator/mysql-innodbcluster -f components/mysql-innodbcluster/upstream/values.yaml --include-crds > components/mysql-innodbcluster/upstream/install.yaml
    silent: false
