version: '3'

tasks:
  hello:
    cmds:
    - echo 'Hello World from Task!'
    silent: true
  update-metallb:
    cmds:
    - helm template metallb metallb/metallb -f components/metallb/upstream/values.yaml  > components/metallb/upstream/install.yaml
    silent: false
  update-logging:
    cmds:
    - helm template loki grafana/loki -f components/grafana-loki/upstream/values.yaml  > components/grafana-loki/upstream/install.yaml
    - helm template minio minio/minio -f components/minio/upstream/values.yaml  > components/minio/upstream/install.yaml
    - helm template grafana grafana/grafana -f components/grafana/upstream/values.yaml  > components/grafana/upstream/install.yaml
    silent: false
  update-vault:
    cmds:
    - helm template vault hashicorp/vault -f components/vault/upstream/values.yaml > components/vault/upstream/install.yaml
    - helm template vso hashicorp/vault-secrets-operator -f components/vault-secrets-operator/upstream/values.yaml --include-crds > components/vault-secrets-operator/upstream/install.yaml
    silent: false
