apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homenw-ingress-cert
spec:
  secretName: homenw-ingress-cert-secret
  dnsNames:
  - "*.nw.home.tak848.me"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
