controller:
  replicaCount: 5
  service:
    loadBalancerIP: 10.3.255.160 # 外部用のIPアドレスを指定
  ingressClassResource:
    name: nginx-external # ここを変更
    enabled: true
    default: true
    controllerValue: "k8s.io/external-ingress-nginx" # default: k8s.io/ingress-nginx
  ingressClass: nginx-external # これも変更
