---
# Source: mysql-innodbcluster/templates/service_account_cluster.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-innodbcluster-sa
  namespace: default
---
# Source: mysql-innodbcluster/templates/cluster_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-innodbcluster-cluster-secret
  namespace: default
stringData:
  rootUser: "root"
  rootHost: "%"
  rootPassword: "password"
---
# Source: mysql-innodbcluster/templates/deployment_cluster.yaml
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-innodbcluster
  namespace: default
spec:
  instances: 3
  tlsUseSelfSigned: true
  router:
    instances: 1


  secretName: mysql-innodbcluster-cluster-secret
  imagePullPolicy : IfNotPresent
  baseServerId: 1000
  version: 8.2.0
  serviceAccountName: mysql-innodbcluster-sa
  datadirVolumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: "10Gi"
  initDB:
    dump:
      name: aaa
      path: /docker-entrypoint-initdb.d
      storage:
        persistentVolumeClaim: 
          claimName: backup-volume-claim-1


  podSpec: 
    containers:
    - name: mysql
      resources:
        limits:
          cpu: 1800m
          memory: 4096Mi
        requests:
          cpu: 900m
          memory: 1024Mi
