apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-cert
  namespace: longhorn-system
spec:
  secretName: longhorn-cert-secret
  dnsNames:
    - "longhorn.j4io.in.tak848.net"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
