apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-kube-aws-kms-user
  namespace: vault
spec:
  encryptedData:
    accessKey: AgAHk6vkCR2WNQ9vcbYvPqAD+8HsL7fuw+IphHABNYIwAJ0RnOucjJpmTr6pr2KLvkJa9JMaMH/Q9C0FcfeO0I/Z/LNbu+qld3y1crrovVgP5PBvGgxa8vQu+oY4G4iVxuglbafyPXmNy127n3gcwaDznnM8oes5SSSyRMekP/raLnwLOtw3jvusrAi2vUnaE/FtMolIv5mcRpm3vRziNGvtmJshoiry2eCznk7bt4wKHsgFeNkAojKEH+hKdhel6LwLx1WRhXEYfTg1oMb6SbAqa02hY3YlpXY1VRJndz7/eXwCaDO2a5VsIZKvsqhJ2RFbB1iA60tHjAmPW2zro1bpeayjUTbvZKIWpZQ6ZXHLf4vGmscF1Aa7uowVtmAsSphYdMaZ+nwkJi0oRFGqKtkcaxAQ8p8Vpc9VfmY7cNz/dB1nmfXb+1gU0hUET0jfOTLlQ8lF0fl5JFy+M+AbIdcSrb9Bo4fT1RQ6M8gqn27jjhfMNO26I3StiNeuBxeFD5b5eIM0cfjlxfjxMpQc0La5r3r9CWYyUGTvKkOn13FD7ZpJ7AkUlre0pYY3LxQLG3yavg9l8Xy60fhw4C0Ii3P6DJCTE5x8ivs3mmPKMw6UnUxQrrRbA/naxja0s/U30PVIC5tLPtQAhodD7wTH+zJhGdq1M17hsYKkpJW49X++S2JDaSRO8of2LfP6E2Y5mOG83/BSFQTDj6mcRCHpIjZiGp1pPA==
    secretKey: AgCUuh8hpR6phM7j9eWFyTKdhb9xLG5YZ/No54xpsr2sshIJFgVMmLRrETo3nIlodp4Y50S9i/SEYxN4oc0877aOrgZNhfMNy9TH//eaSwD3H3wYaaQPMHeRsN79y9MVTFNW6lVoHdO0JMxll3ldMygmXwZOLqyhO0trCIq9uqpFwSDUQs/UI5Xc6xquynM3oqQIDSq7K7NtLsJMH9azA4Y/FfnaYuJyIPCP3sxuVl9c2n9+6sf/z8ip10qK8Te2Rl52bnXSKnQtn6pTY6IODEfKCifaDVko53kXV91sKCd69aFwmCWltQLIN1oGn4v3HH+p6Spd+Ak56IcfAVQBd9ob5nsDaJzdZ5Iu6yy6iTPE2d6E+9bP13vWwX88hIFG+cNAT3hAmwQAY8jwWY+6jIgr6bxeY9bHRTp0KoVGE7XKyAzEZw2CQ7AYJZWG4tip/BQ1eHyVe34W8+yV09JVZH+BHYS9X8Gs0kRU8xUGX6virMqNYHGtITZYajLHhSeX8dERnVbPRxENkD/GsTfrglbjB6SwoNOxpFDZcuf8V01KYdM397eDOmWF79fEf8nFe27vwCzJySSHcEK/JlUBusO9uE53MxU3rToKsKiqLD9g3gNLG8VVx20yfvP9VdDeqzqbLQ2x7WMdTOf3ZPFAarS2VVLbccILOmsOfTl+5Qv9m5JXRLx6ux2M91EzIZ30fBQSbJOxMIG1yz0ZzCxzyIGBvHIsOYn3+byTnTk4b6jyL3/gv8YOi91T
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: home-kube-aws-kms-user
      namespace: vault
