apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: common.yaml
- path: metallb.yaml
- path: vault.yaml
# - path: vault-secrets-operator.yaml
# - path: logging.yaml
