apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ./all-apps
patches:
- path: argocd.yaml
- path: common.yaml
- path: metallb.yaml
- path: vault.yaml
- path: vault-secrets-operator.yaml
- path: logging.yaml
