apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: all-apps.yaml
- path: argocd.yaml
- path: common.yaml
- path: metallb.yaml
- path: vault.yaml
- path: vault-secrets-operator.yaml
- path: mysql-operator.yaml
- path: logging.yaml
- path: logging-crds.yaml
- path: homenw.yaml
