controller:
  electionID: ingress-controller-external-leader
  replicaCount: 5
  service:
    loadBalancerIP: 10.3.255.160 # 外部用のIPアドレスを指定
  ingressClassResource:
    name: nginx-external # ここを変更
    enabled: true
    default: true
  ingressClass: nginx-external # これも変更
